# Generated by Django 5.1.7 on 2025-03-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('CIVILIAN', 'Civilian'), ('ADMIN', 'Village Authority Admin')], max_length=20)),
                ('registration_step', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('id_proof_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('VOTER_ID', 'Voter ID'), ('PAN', 'PAN Card'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport'), ('RATION_CARD', 'Ration Card'), ('OTHER', 'Other')], max_length=20)),
                ('id_proof_file', models.FileField(upload_to='id_proofs/')),
                ('authority_position', models.CharField(blank=True, max_length=100)),
                ('government_id', models.CharField(blank=True, max_length=150)),
                ('department_name', models.CharField(max_length=150)),
                ('work_location', models.CharField(max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('family_members', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
