# Generated by Django 5.1.7 on 2025-03-26 17:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id_proof_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='id_proofs'),
        ),
    ]
