# Generated by Django 5.1.7 on 2025-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_useraccount_groups_useraccount_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Civilian', 'Civilian'), ('Authority', 'Authority')], max_length=20),
        ),
    ]
