# Generated by Django 5.1.7 on 2025-03-27 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_useraccount_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feedback_type', models.CharField(choices=[('COMPLAINT', 'Complaint'), ('SUGGESTION', 'Suggestion'), ('COMMENT', 'General Comment'), ('IDEA', 'Policy Idea')], max_length=20)),
                ('category', models.CharField(choices=[('INFRASTRUCTURE', 'Infrastructure (Roads, Bridges, etc.)'), ('TRANSPORTATION', 'Transportation'), ('EDUCATION', 'Education'), ('HEALTHCARE', 'Healthcare'), ('SANITATION', 'Sanitation & Waste Management'), ('WATER', 'Water Supply'), ('ELECTRICITY', 'Electricity'), ('PUBLIC_SAFETY', 'Public Safety'), ('ENVIRONMENT', 'Environment'), ('HOUSING', 'Housing'), ('TAXATION', 'Taxation'), ('WELFARE', 'Social Welfare'), ('EMPLOYMENT', 'Employment'), ('AGRICULTURE', 'Agriculture'), ('TOURISM', 'Tourism'), ('CULTURE', 'Arts & Culture'), ('OTHER', 'Other')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='authentication.useraccount')),
            ],
        ),
    ]
