# Generated by Django 5.1.7 on 2025-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
