# Generated by Django 5.1.7 on 2025-03-28 15:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='feedbackimage'),
        ),
    ]
