# Generated by Django 5.1.7 on 2025-03-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
    ]
