# Generated by Django 5.1.7 on 2025-10-11 19:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_feedback_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='feedback_image'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['category'], name='feedback_fe_categor_9a32a3_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status'], name='feedback_fe_status_35d074_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['urgency'], name='feedback_fe_urgency_1ac3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['created_at'], name='feedback_fe_created_84c297_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['location'], name='feedback_fe_locatio_d4c28d_idx'),
        ),
    ]
