# Generated by Django 5.1.7 on 2025-10-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_latitude_feedback_longitude_feedback_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='longitude',
        ),
    ]
