# Generated by Django 5.1.7 on 2025-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_remove_feedback_latitude_remove_feedback_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
